name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 🔍 Debug — показать файлы
        run: ls -la

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: latest
          command: "android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
